<?php

namespace AppBundle\Repository;

/**
 * MedicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMedicationByname($medic)
    {
        $qb = $this
            ->createQueryBuilder('m')
            ->where('m.name LIKE :medic')
            ->orWhere('m.name LIKE :medic')
            ->setParameters(
                array(
                    'medic'=>"%".$medic."%",
                ));
        return $qb
            ->getQuery()
            ->getResult();
    }
}
