<?php

namespace AppBundle\Repository;

/**
 * PharmacyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PharmacyRepository extends \Doctrine\ORM\EntityRepository
{
}
