<?php

namespace AppBundle\Repository;

/**
 * PrescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrescriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPrescriptionByReferenceQueryBuilder($reference)
    {
        return $this
            ->createQueryBuilder('p')
            ->where('p.reference = :reference')
            ->setParameter('reference', $reference)
            ;
    }
}
