<?php

namespace AppBundle\Repository;

/**
 * PrescriptionMedicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrescriptionMedicationRepository extends \Doctrine\ORM\EntityRepository
{
}
