# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

#    role_hierarchy:
#        ROLE_DOCTOR: [ROLE_DOCTOR]
#        ROLE_PHARMACY: [ROLE_PHARMACY]
#        ROLE_SUPPLIER: [ROLE_SUPPLIER]
#        ROLE_ADMIN: [ROLE_DOCTOR, ROLE_PATIENT,ROLE_PHARMACY,ROLE_SUPPLIER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: homepage
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true
            access_denied_handler: AppBundle\Security\AccessDeniedHandler

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: ^/patient/, role: ROLE_USER }
#        - { path: ^/doctor/, role: ROLE_DOCTOR }
#        - { path: ^/pharmacy/, role: ROLE_PHARMACY}
#        - { path: ^/supplier/, role: ROLE_SUPPLIER }